const escapeHtml = (value) => String(value)
  .replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;')
  .replaceAll('"', '&quot;').replaceAll("'", '&#39;');

export function renderInventoryBranchBalances({ companyId = 1, branchId = '' } = {}) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>ERP Portal · Branch balances</title>
<style>body{font-family:system-ui,sans-serif;background:#f6f7f9;color:#17202a;margin:0}main{max-width:1100px;margin:0 auto;padding:32px}h1{margin:0 0 8px}.scope{display:flex;gap:12px;flex-wrap:wrap;background:#fff;padding:16px;border:1px solid #dfe3e8;border-radius:10px}.scope label{display:flex;flex-direction:column;gap:4px;font-size:13px}.scope input{padding:8px;border:1px solid #b8c0ca;border-radius:6px}.scope button{align-self:end;padding:9px 16px;border:0;border-radius:6px;background:#166534;color:#fff;cursor:pointer}.state{margin:16px 0;padding:12px;border-radius:8px;background:#eef2ff}.state.denied{background:#fff1f2;color:#9f1239}.state.transport{background:#fff7ed;color:#9a3412}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:12px}.card{background:#fff;border:1px solid #dfe3e8;border-radius:10px;padding:16px}.muted{color:#667085}</style></head><body><main>
<h1>Inventory · Branch balances</h1><p class="muted">Branch aggregate through the authenticated Inventory gateway; no direct database access.</p>
<form id="branch-scope" class="scope"><label>Company ID<input name="companyId" type="number" min="1" value="${escapeHtml(companyId)}" required></label><label>Branch ID<input name="branchId" type="number" min="1" value="${escapeHtml(branchId)}" required></label><button type="submit">Load branch balances</button></form>
<section id="branch-state" class="state" aria-live="polite">Enter a company and branch scope.</section><section id="branch-items" class="cards" aria-label="Branch balances"></section>
<script>
const form=document.getElementById('branch-scope'),state=document.getElementById('branch-state'),items=document.getElementById('branch-items');
const setState=(text,kind='')=>{state.textContent=text;state.className='state '+kind};
const escape=(value)=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
form.addEventListener('submit',async(event)=>{event.preventDefault();items.replaceChildren();setState('Loading branch balances…');const data=new FormData(form);const correlationId=crypto.randomUUID();const query=new URLSearchParams({companyId:String(Number(data.get('companyId'))),branchId:String(Number(data.get('branchId'))),correlationId});try{const [availability,valuation]=await Promise.all([fetch('/api/inventory/branch-availability?'+query,{headers:{'x-correlation-id':correlationId}}),fetch('/api/inventory/branch-valuation?'+query,{headers:{'x-correlation-id':correlationId}})]);if([availability,valuation].some((response)=>response.status===401||response.status===403)){setState('Access denied for this company/branch scope.','denied');return}if(!availability.ok||!valuation.ok){setState('Inventory gateway is unavailable. Try again later.','transport');return}const stock=await availability.json(),costs=await valuation.json(),costByKey=new Map((costs.items??[]).map((row)=>[row.productCode+'/'+row.variantCode,row]));const rows=stock.items??[];if(!rows.length){setState('No branch balance rows returned.');return}setState(costs.financialsVisible?'Branch balances and permitted valuation loaded.':'Branch balances loaded; financial values are hidden.');items.innerHTML=rows.map((row)=>{const cost=costByKey.get(row.productCode+'/'+row.variantCode);const value=costs.financialsVisible&&cost?.value!==undefined?'<p>Value: '+escape(cost.value)+'</p>':'';return '<article class="card"><strong>'+escape(row.productCode)+' / '+escape(row.variantCode)+'</strong><p>On hand: '+escape(row.onHand)+'</p><p>Reserved: '+escape(row.reserved)+'</p><p>Available: '+escape(row.available)+'</p><p>Warehouses: '+escape(row.warehouseCount)+'</p>'+value+'</article>'}).join('')}catch{setState('Inventory gateway is unavailable. Try again later.','transport')}});
</script></main></body></html>`;
}
