const escapeHtml = (value) => String(value)
  .replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;')
  .replaceAll('"', '&quot;').replaceAll("'", '&#39;');

export function renderInventoryImport({ companyId = 1, branchId = '', warehouseId = '' } = {}) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>ERP Portal · Inventory Import Review</title><style>
body{font-family:system-ui,sans-serif;background:#f6f7f9;color:#17202a;margin:0}main{max-width:1100px;margin:auto;padding:32px}h1{margin:0 0 8px}.scope{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px;background:#fff;padding:16px;border:1px solid #dfe3e8;border-radius:10px}.scope label{display:flex;flex-direction:column;gap:4px;font-size:13px}.scope input,.scope textarea{padding:8px;border:1px solid #b8c0ca;border-radius:6px}.scope textarea{min-height:100px;grid-column:1/-1;font-family:monospace}.scope button{justify-self:start;padding:9px 16px;border:0;border-radius:6px;background:#b45309;color:#fff}.state{margin:16px 0;padding:12px;border-radius:8px;background:#eef2ff}.denied{background:#fff1f2;color:#9f1239}.transport{background:#fff7ed;color:#9a3412}.review{background:#fff;border:1px solid #dfe3e8;border-radius:10px;padding:16px}.error{color:#9f1239}.muted{color:#667085}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:8px;border-bottom:1px solid #edf0f2}
</style></head><body><main><h1>Inventory Import Review</h1><p class="muted">Preview only. No inventory mutation is performed from this screen.</p>
<form id="import-preview" class="scope"><label>Company ID<input name="companyId" type="number" min="1" value="${escapeHtml(companyId)}" required></label><label>Branch ID<input name="branchId" type="number" min="1" value="${escapeHtml(branchId)}" required></label><label>Warehouse ID<input name="warehouseId" type="number" min="1" value="${escapeHtml(warehouseId)}" required></label><label>Headers<input name="headers" value="product_code,variant_code,quantity" required></label><label>Rows JSON<textarea name="rows">[{"rowNumber":1,"productCode":"SKU-1","variantCode":"","rawQuantity":"2"}]</textarea></label><button type="submit">Preview import</button></form>
<section id="import-state" class="state" aria-live="polite">Enter scope and review the preview.</section><section id="import-review" class="review"></section>
<script>
const form=document.getElementById('import-preview'),state=document.getElementById('import-state'),review=document.getElementById('import-review');const esc=(v)=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');const stateFor=(text,kind='')=>{state.textContent=text;state.className='state '+kind};
form.addEventListener('submit',async(e)=>{e.preventDefault();review.replaceChildren();stateFor('Validating and previewing import…');const data=new FormData(form);let rows;try{rows=JSON.parse(String(data.get('rows')||'[]'))}catch{stateFor('Rows JSON is invalid.','denied');return}const correlationId=crypto.randomUUID(),payload={companyId:Number(data.get('companyId')),branchId:Number(data.get('branchId')),warehouseId:Number(data.get('warehouseId')),headers:String(data.get('headers')).split(',').map((v)=>v.trim()).filter(Boolean),rows,correlationId};try{const response=await fetch('/api/inventory/import/preview',{method:'POST',headers:{'content-type':'application/json','x-correlation-id':correlationId},body:JSON.stringify(payload)});if(response.status===401||response.status===403){stateFor('Import preview access denied for this scope.','denied');return}if(!response.ok){stateFor('Inventory gateway is unavailable. Try again later.','transport');return}const body=await response.json();stateFor(body.accepted?'Preview accepted; review rows before staging.':'Preview contains errors; nothing was staged.');const errors=(body.headerErrors||[]).map((item)=>'<li class="error">'+esc(item)+'</li>').join('');const rowsHtml=(body.rows||[]).map((row)=>'<tr><td>'+esc(row.rowNumber)+'</td><td>'+esc(row.productCode)+'</td><td>'+esc(row.variantCode)+'</td><td>'+esc(row.action)+'</td><td>'+esc(row.reason||'')+'</td></tr>').join('');review.innerHTML='<p>Duplicate rows: '+esc(body.duplicateRows||0)+' · Staged units preview: '+esc(body.stagedUnits||0)+'</p>'+(errors?'<ul>'+errors+'</ul>':'')+'<table><thead><tr><th>Row</th><th>Product</th><th>Variant</th><th>Action</th><th>Reason</th></tr></thead><tbody>'+rowsHtml+'</tbody></table>'}catch{stateFor('Inventory gateway is unavailable. Try again later.','transport')}});
</script></main></body></html>`;
}
