const escapeHtml = (value) => String(value)
  .replaceAll('&', '&amp;')
  .replaceAll('<', '&lt;')
  .replaceAll('>', '&gt;')
  .replaceAll('"', '&quot;')
  .replaceAll("'", '&#39;');

export function renderInventoryLocations({ companyId = 1, branchId = '', warehouseId = '' } = {}) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>ERP Portal · Inventory Locations</title><style>body{font-family:system-ui,sans-serif;background:#f6f7f9;color:#17202a;margin:0}main{max-width:1100px;margin:auto;padding:32px}h1{margin:0 0 8px}.scope{display:flex;gap:12px;flex-wrap:wrap;background:#fff;padding:16px;border:1px solid #dfe3e8;border-radius:10px}.scope label{display:flex;flex-direction:column;gap:4px;font-size:13px}.scope input{padding:8px;border:1px solid #b8c0ca;border-radius:6px}.scope button{align-self:end;padding:9px 16px;border:0;border-radius:6px;background:#334155;color:#fff}.state{margin:16px 0;padding:12px;border-radius:8px;background:#eef2ff}.denied{background:#fff1f2;color:#9f1239}.transport{background:#fff7ed;color:#9a3412}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.card{background:#fff;border:1px solid #dfe3e8;border-radius:10px;padding:16px}.muted{color:#667085}table{width:100%;border-collapse:collapse;background:#fff}th,td{text-align:left;padding:9px;border-bottom:1px solid #edf0f2}</style></head><body><main>
<h1>Inventory · Warehouses and locations</h1><p class="muted">Branch and warehouse scoped reads through the authenticated Inventory gateway.</p>
<form id="locations-scope" class="scope"><label>Company ID<input name="companyId" type="number" min="1" value="${escapeHtml(companyId)}" required></label><label>Branch ID<input name="branchId" type="number" min="1" value="${escapeHtml(branchId)}" required></label><label>Warehouse ID<input name="warehouseId" type="number" min="1" value="${escapeHtml(warehouseId)}" required></label><button type="submit">Load locations</button></form>
<section id="locations-state" class="state" aria-live="polite">Enter a company, branch, and warehouse scope.</section><section id="locations-content" class="grid"></section>
<script>const form=document.getElementById('locations-scope'),state=document.getElementById('locations-state'),content=document.getElementById('locations-content');const esc=(v)=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');const setState=(text,kind='')=>{state.textContent=text;state.className='state '+kind};form.addEventListener('submit',async(e)=>{e.preventDefault();content.replaceChildren();setState('Loading warehouses and locations…');const data=new FormData(form),companyId=Number(data.get('companyId')),branchId=Number(data.get('branchId')),warehouseId=Number(data.get('warehouseId')),correlationId=crypto.randomUUID();const query='companyId='+companyId+'&branchId='+branchId+'&warehouseId='+warehouseId+'&correlationId='+correlationId;try{const [warehouses,locations]=await Promise.all([fetch('/api/inventory/warehouses?'+query,{headers:{'x-correlation-id':correlationId}}),fetch('/api/inventory/locations?'+query,{headers:{'x-correlation-id':correlationId}})]);if([warehouses.status,locations.status].some((status)=>status===401||status===403)){setState('Access denied for this company/branch/warehouse scope.','denied');return}if(!warehouses.ok||!locations.ok){setState('Inventory gateway is unavailable. Try again later.','transport');return}const warehouseBody=await warehouses.json(),locationBody=await locations.json();setState('Warehouses and locations loaded.');const warehouseRows=warehouseBody.items||[],locationRows=locationBody.items||[];content.innerHTML='<article class="card"><h2>Warehouses</h2>'+(warehouseRows.length?'<table><thead><tr><th>Code</th><th>Name</th><th>Branch</th><th>Active</th></tr></thead><tbody>'+warehouseRows.map((row)=>'<tr><td>'+esc(row.code)+'</td><td>'+esc(row.name)+'</td><td>'+esc(row.branchId)+'</td><td>'+esc(row.active)+'</td></tr>').join('')+'</tbody></table>':'<p class="muted">No warehouses returned.</p>')+'</article><article class="card"><h2>Locations</h2>'+(locationRows.length?'<table><thead><tr><th>Code</th><th>Name</th><th>Type</th><th>Usage</th><th>Active</th></tr></thead><tbody>'+locationRows.map((row)=>'<tr><td>'+esc(row.code)+'</td><td>'+esc(row.name)+'</td><td>'+esc(row.locationType)+'</td><td>'+esc(row.usage)+'</td><td>'+esc(row.active)+'</td></tr>').join('')+'</tbody></table>':'<p class="muted">No locations returned.</p>')+'</article>'}catch{setState('Inventory gateway is unavailable. Try again later.','transport')}});</script></main></body></html>`;
}
