const escapeHtml = (value) => String(value)
  .replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;')
  .replaceAll('"', '&quot;').replaceAll("'", '&#39;');

export function renderInventoryImport({ companyId = 1, branchId = '', warehouseId = '' } = {}) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>ERP Portal · Inventory Import Review</title><style>
body{font-family:system-ui,sans-serif;background:#f6f7f9;color:#17202a;margin:0}main{max-width:1100px;margin:auto;padding:32px}h1{margin:0 0 8px}.scope{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px;background:#fff;padding:16px;border:1px solid #dfe3e8;border-radius:10px}.scope label{display:flex;flex-direction:column;gap:4px;font-size:13px}.scope input,.scope textarea{padding:8px;border:1px solid #b8c0ca;border-radius:6px}.scope textarea{min-height:100px;grid-column:1/-1;font-family:monospace}.scope button{justify-self:start;padding:9px 16px;border:0;border-radius:6px;background:#b45309;color:#fff}.state{margin:16px 0;padding:12px;border-radius:8px;background:#eef2ff}.denied{background:#fff1f2;color:#9f1239}.transport{background:#fff7ed;color:#9a3412}.review{background:#fff;border:1px solid #dfe3e8;border-radius:10px;padding:16px}.error{color:#9f1239}.muted{color:#667085}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:8px;border-bottom:1px solid #edf0f2}
</style></head><body><main><h1>Inventory Import Review</h1><p class="muted">Preview first, then explicitly stage or apply the reviewed count session. Catalog identity failures are shown per row and block both actions. Direct apply is Development-only and permissioned.</p>
<form id="import-preview" class="scope"><label>Company ID<input name="companyId" type="number" min="1" value="${escapeHtml(companyId)}" required></label><label>Branch ID<input name="branchId" type="number" min="1" value="${escapeHtml(branchId)}" required></label><label>Warehouse ID<input name="warehouseId" type="number" min="1" value="${escapeHtml(warehouseId)}" required></label><label>Headers<input name="headers" value="product_code,variant_code,quantity" required></label><label>Reference<input name="reference" value="warehouse-import-review" required></label><label>Rows JSON<textarea name="rows">[{"rowNumber":1,"productCode":"SKU-1","variantCode":"","rawQuantity":"2"}]</textarea></label><button type="submit">Preview import</button><button id="stage-import" type="button" disabled>Stage reviewed import</button><button id="apply-import" type="button" disabled>Apply reviewed import (Dev)</button></form>
<section class="scope"><h2>Explicit Catalog identity provisioning</h2><p class="muted">Use this only when the Catalog identity is missing. It does not stage or apply stock; run Preview import again after it succeeds.</p><label>Product code<input id="catalog-product-code" value="SKU-1" required></label><label>Variant code<input id="catalog-variant-code" value="BLUE-M" required></label><label>Display name<input id="catalog-display-name" value="Blue medium" required></label><label>External ID<input id="catalog-external-id" value=""></label><label>Barcode<input id="catalog-barcode" value=""></label><label>Source version<input id="catalog-source-version" value="portal-import-v1" required></label><button id="provision-catalog" type="button">Provision Catalog identity</button></section>
<section id="import-state" class="state" aria-live="polite">Enter scope and review the preview.</section><section id="import-review" class="review"></section>
<script>
const form=document.getElementById('import-preview'),state=document.getElementById('import-state'),review=document.getElementById('import-review'),stageButton=document.getElementById('stage-import'),applyButton=document.getElementById('apply-import'),provisionButton=document.getElementById('provision-catalog');let reviewedPayload=null;const esc=(v)=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');const display=(v)=>v===null||v===undefined||v===''?'—':v;const stateFor=(text,kind='')=>{state.textContent=text;state.className='state '+kind};
provisionButton.addEventListener('click',async()=>{provisionButton.disabled=true;const data=new FormData(form),correlationId=crypto.randomUUID(),payload={companyId:Number(data.get('companyId')),productCode:String(document.getElementById('catalog-product-code').value).trim(),variantCode:String(document.getElementById('catalog-variant-code').value).trim(),displayName:String(document.getElementById('catalog-display-name').value).trim(),externalId:String(document.getElementById('catalog-external-id').value).trim(),barcode:String(document.getElementById('catalog-barcode').value).trim(),sourceVersion:String(document.getElementById('catalog-source-version').value).trim(),active:true,correlationId};if(!payload.productCode||!payload.variantCode||!payload.displayName||!payload.sourceVersion){stateFor('Catalog provisioning requires product, variant, display name, and source version.','denied');provisionButton.disabled=false;return}try{const response=await fetch('/api/inventory/catalog/product-variant',{method:'POST',headers:{'content-type':'application/json','x-correlation-id':correlationId},body:JSON.stringify(payload)});if(response.status===401||response.status===403){stateFor('Catalog provisioning access denied.','denied');return}if(!response.ok){stateFor('Catalog provisioning was rejected; no stock was changed.','denied');return}const body=await response.json();stateFor('Catalog identity provisioned: '+(body.productId||'')+'/'+(body.variantId||'')+'. Run Preview import again.')}catch{stateFor('Inventory gateway is unavailable. Try again later.','transport')}finally{provisionButton.disabled=false}});
form.addEventListener('submit',async(e)=>{e.preventDefault();review.replaceChildren();stageButton.disabled=true;applyButton.disabled=true;reviewedPayload=null;stateFor('Validating and previewing import…');const data=new FormData(form);let rows;try{rows=JSON.parse(String(data.get('rows')||'[]'))}catch{stateFor('Rows JSON is invalid.','denied');return}const correlationId=crypto.randomUUID(),payload={companyId:Number(data.get('companyId')),branchId:Number(data.get('branchId')),warehouseId:Number(data.get('warehouseId')),headers:String(data.get('headers')).split(',').map((v)=>v.trim()).filter(Boolean),rows,correlationId},reference=String(data.get('reference'));try{const response=await fetch('/api/inventory/import/preview',{method:'POST',headers:{'content-type':'application/json','x-correlation-id':correlationId},body:JSON.stringify(payload)});if(response.status===401||response.status===403){stateFor('Import preview access denied for this scope.','denied');return}if(!response.ok){stateFor('Inventory gateway is unavailable. Try again later.','transport');return}const body=await response.json();const valid=body.accepted&&!(body.rows||[]).some((row)=>row.action!=='would_stage');stateFor(valid?'Preview accepted; review rows before staging.':'Preview contains errors; nothing can be staged.');const errors=(body.headerErrors||[]).map((item)=>'<li class="error">'+esc(item)+'</li>').join('');const rowsHtml=(body.rows||[]).map((row)=>'<tr><td>'+esc(row.rowNumber)+'</td><td>'+esc(row.productCode)+'</td><td>'+esc(row.variantCode)+'</td><td>'+esc(row.catalogProductId||'—')+'</td><td>'+esc(row.catalogVariantId||'—')+'</td><td>'+esc(row.catalogSourceVersion||'—')+'</td><td>'+esc(display(row.incomingUnitCost))+'</td><td>'+esc(display(row.beforeCostValue))+'</td><td>'+esc(display(row.afterCostValue))+'</td><td>'+esc(display(row.costValueDelta))+'</td><td>'+esc(display(row.costPreviewStatus))+'</td><td>'+esc(row.action)+'</td><td>'+esc(row.reason||'')+'</td></tr>').join('');review.innerHTML='<p>Duplicate rows: '+esc(body.duplicateRows||0)+' · Staged units preview: '+esc(body.stagedUnits||0)+'</p>'+(errors?'<ul>'+errors+'</ul>':'')+'<table><thead><tr><th>Row</th><th>Product</th><th>Variant</th><th>Catalog product ID</th><th>Catalog variant ID</th><th>Catalog version</th><th>Incoming unit cost</th><th>Before cost</th><th>After cost</th><th>Cost delta</th><th>Cost status</th><th>Action</th><th>Reason</th></tr></thead><tbody>'+rowsHtml+'</tbody></table>';if(valid){reviewedPayload={...payload,reference};stageButton.disabled=false;applyButton.disabled=false}}catch{stateFor('Inventory gateway is unavailable. Try again later.','transport')}});
stageButton.addEventListener('click',async()=>{if(!reviewedPayload)return;stageButton.disabled=true;const correlationId=crypto.randomUUID();try{const response=await fetch('/api/inventory/import/stage',{method:'POST',headers:{'content-type':'application/json','x-correlation-id':correlationId},body:JSON.stringify({...reviewedPayload,idempotencyKey:crypto.randomUUID(),correlationId})});if(response.status===401||response.status===403){stateFor('Import staging access denied for this scope.','denied');return}if(!response.ok){stateFor('Import staging was rejected; nothing was applied.','transport');return}const body=await response.json();stateFor((body.replayed?'Staged import replayed safely. ':'Import staged for count review. ')+(body.operationId||''))}catch{stateFor('Inventory gateway is unavailable. Try again later.','transport')}});
applyButton.addEventListener('click',async()=>{if(!reviewedPayload){stateFor('Run and approve a valid Preview before applying.','denied');return}applyButton.disabled=true;const correlationId=crypto.randomUUID();try{const response=await fetch('/api/inventory/import/apply',{method:'POST',headers:{'content-type':'application/json','x-correlation-id':correlationId},body:JSON.stringify({...reviewedPayload,idempotencyKey:crypto.randomUUID(),correlationId})});if(response.status===401||response.status===403){stateFor('Import apply access denied for this scope.','denied');return}if(response.status===412){stateFor('Import apply is disabled in this environment.','denied');return}if(!response.ok){stateFor('Import apply was rejected; stock was not applied.','transport');return}const body=await response.json();stateFor((body.replayed?'Import replayed safely. ':'Import applied through the count workflow. ')+(body.operationId||''))}catch{stateFor('Inventory gateway is unavailable. Try again later.','transport')}finally{applyButton.disabled=!reviewedPayload}});
</script></main></body></html>`;
}
