const escapeHtml = (value) => String(value)
  .replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;')
  .replaceAll('"', '&quot;').replaceAll("'", '&#39;');

export function renderInventoryMoves({ companyId = 1, warehouseId = '' } = {}) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>ERP Portal · Inventory Moves</title><style>body{font-family:system-ui,sans-serif;background:#f6f7f9;color:#17202a;margin:0}main{max-width:780px;margin:auto;padding:32px}h1{margin:0 0 8px}.muted{color:#667085}.card{background:#fff;border:1px solid #dfe3e8;border-radius:10px;padding:18px}.field{display:flex;flex-direction:column;gap:4px;margin:10px 0}.field input,.field select{padding:8px;border:1px solid #b8c0ca;border-radius:6px}.button{padding:9px 16px;border:0;border-radius:6px;background:#1d4ed8;color:#fff;cursor:pointer}.state{margin:16px 0;padding:12px;border-radius:8px;background:#eef2ff}.denied{background:#fff1f2;color:#9f1239}.transport{background:#fff7ed;color:#9a3412}.warning{background:#fff7ed;color:#9a3412}</style></head><body><main><h1>Inventory · Stock moves</h1><p class="muted">Receive, issue, or adjust stock through the authenticated Inventory gateway. Transit dispatch/receipt is intentionally not exposed here.</p><section id="move-state" class="state" aria-live="polite">Submit an authorized stock operation.</section><form id="move-form" class="card"><label class="field">Operation<select name="operation"><option value="receive">Receive</option><option value="issue">Issue</option><option value="adjust">Adjust</option></select></label><label class="field">Company ID<input name="companyId" type="number" min="1" value="${escapeHtml(companyId)}" required></label><label class="field">Warehouse ID<input name="warehouseId" type="number" min="1" value="${escapeHtml(warehouseId)}" required></label><label class="field">Product code<input name="productCode" required></label><label class="field">Variant code<input name="variantCode" required></label><label class="field">Quantity<input name="quantity" type="number" step="any" min="0.000001" required></label><label class="field">Unit cost (Receive/Adjust only)<input name="unitCost" type="number" step="any" min="0" value="0"></label><label class="field">Source reference / reason<input name="sourceReference" required></label><button class="button" type="submit">Apply stock operation</button></form><script>
const form=document.getElementById('move-form'),state=document.getElementById('move-state');const setState=(text,kind='')=>{state.textContent=text;state.className='state '+kind};form.addEventListener('submit',async(e)=>{e.preventDefault();setState('Applying stock operation…');const data=new FormData(form),operation=String(data.get('operation')),correlationId=crypto.randomUUID(),idempotencyKey=crypto.randomUUID(),quantity=Number(data.get('quantity')),base={companyId:Number(data.get('companyId')),warehouseId:Number(data.get('warehouseId')),productCode:String(data.get('productCode')),variantCode:String(data.get('variantCode')),correlationId,idempotencyKey};const payload=operation==='receive'?{...base,quantity,sourceReference:String(data.get('sourceReference')),unitCost:Number(data.get('unitCost'))}:operation==='issue'?{...base,quantity,sourceReference:String(data.get('sourceReference'))}:{...base,quantityDelta:quantity,reason:String(data.get('sourceReference')),unitCost:Number(data.get('unitCost'))};try{const response=await fetch('/api/inventory/stock/'+operation,{method:'POST',headers:{'content-type':'application/json','x-correlation-id':correlationId},body:JSON.stringify(payload)});if(response.status===401||response.status===403){setState('Stock operation denied for this caller or warehouse scope.','denied');return}if(!response.ok){setState('Inventory gateway rejected the operation.','transport');return}const body=await response.json();setState((body.replayed?'Operation already applied safely. ':'Stock operation applied. ')+(body.operationId||''));}catch{setState('Inventory gateway is unavailable. Try again later.','transport')}});</script></main></body></html>`;
}
