const escapeHtml = (value) => String(value)
  .replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;')
  .replaceAll('"', '&quot;').replaceAll("'", '&#39;');

export function renderInventoryValuation({ companyId = 1, warehouseId = '' } = {}) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>ERP Portal · Inventory Valuation</title><style>
body{font-family:system-ui,sans-serif;background:#f6f7f9;color:#17202a;margin:0}main{max-width:1100px;margin:auto;padding:32px}h1{margin:0 0 8px}.scope{display:flex;gap:12px;flex-wrap:wrap;background:#fff;padding:16px;border:1px solid #dfe3e8;border-radius:10px}.scope label{display:flex;flex-direction:column;gap:4px;font-size:13px}.scope input{padding:8px;border:1px solid #b8c0ca;border-radius:6px}.scope button{align-self:end;padding:9px 16px;border:0;border-radius:6px;background:#7c3aed;color:#fff}.state{margin:16px 0;padding:12px;border-radius:8px;background:#eef2ff}.denied{background:#fff1f2;color:#9f1239}.transport{background:#fff7ed;color:#9a3412}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:12px}.card{background:#fff;border:1px solid #dfe3e8;border-radius:10px;padding:16px}.muted{color:#667085}.financial{border-left:4px solid #7c3aed}.masked{border-left:4px solid #94a3b8}
</style></head><body><main><h1>Inventory Valuation</h1><p class="muted">Scoped valuation read through the Inventory gateway. Financial details follow the service authorization decision.</p>
<form id="valuation-scope" class="scope"><label>Company ID<input name="companyId" type="number" min="1" value="${escapeHtml(companyId)}" required></label><label>Warehouse ID<input name="warehouseId" type="number" min="1" value="${escapeHtml(warehouseId)}" required></label><button type="submit">Load valuation</button></form>
<section id="valuation-state" class="state" aria-live="polite">Enter a company and warehouse scope.</section><section id="valuation-items" class="grid"></section>
<script>
const form=document.getElementById('valuation-scope'),state=document.getElementById('valuation-state'),items=document.getElementById('valuation-items');
const esc=(v)=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const stateFor=(text,kind='')=>{state.textContent=text;state.className='state '+kind};
form.addEventListener('submit',async(e)=>{e.preventDefault();items.replaceChildren();stateFor('Loading valuation…');const data=new FormData(form),companyId=Number(data.get('companyId')),warehouseId=Number(data.get('warehouseId')),correlationId=crypto.randomUUID();try{const response=await fetch('/api/inventory/valuation?companyId='+encodeURIComponent(companyId)+'&warehouseId='+encodeURIComponent(warehouseId)+'&correlationId='+encodeURIComponent(correlationId),{headers:{'x-correlation-id':correlationId}});if(response.status===401||response.status===403){stateFor('Valuation access denied for this company/warehouse scope.','denied');return}if(!response.ok){stateFor('Inventory gateway is unavailable. Try again later.','transport');return}const body=await response.json(),visible=body.financialsVisible===true;stateFor(visible?'Valuation loaded with authorized financial details.':'Valuation loaded; financial details are hidden for this caller.');const rows=Array.isArray(body.items)?body.items:[];items.innerHTML=rows.length?rows.map((row)=>'<article class="card '+(visible?'financial':'masked')+'"><strong>'+esc(row.productCode)+' / '+esc(row.variantCode)+'</strong><p>Quantity: '+esc(row.quantity)+'</p><p>Costing method: '+esc(row.costingMethod||'not disclosed')+'</p>'+(visible?'<p>Value: '+esc(row.value??'not disclosed')+'</p><p>Average unit cost: '+esc(row.averageUnitCost??'not disclosed')+'</p>':'<p class="muted">Cost and value details are permission-masked.</p>')+'</article>').join(''):'<p class="muted">No valuation rows returned.</p>'}catch{stateFor('Inventory gateway is unavailable. Try again later.','transport')}});
</script></main></body></html>`;
}
